#!/usr/bin/env node

var fs = require('fs');

var args = process.argv.slice(2)

function combineText (fileArr) {
	var time = function(name) {
	  var start = Date.now();
	  return function() {
	    console.log('[time] %s: %dms', name, Date.now() - start);
	  };
	};

	var done = time('reading file');

	  for (var i = 0;i <fileArr.length; i++) {
	  	
	  	fs.readFile(fileArr[i], { encoding: 'utf8' }, function(err, contents) {
	  		console.log(contents);
	  		done();
	  });
	};

	
		
};

combineText(args);





