#!/usr/bin/env node

var fs = require('fs');

var args = process.argv.slice(2)

function combineText (fileArr) {

  for (var i = 0;i <fileArr.length; i++) {
  	
  	fs.readFile(fileArr[i], { encoding: 'utf8' }, function(err, contents) {
  		console.log(contents);
  });
}

}

combineText(args);

